version: 2
archives:
  - format_overrides:
    - goos: windows
      formats: [zip]
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - darwin
    - windows
    - linux
    goarch:
    - amd64
    - "386"
    - arm64
    ldflags:
    - -s -w -X github.com/jfrappier/tfsprout/version.Version={{.Version}} -X github.com/jfrappier/tfsprout/version.VersionPrerelease= -X github.com/jfrappier/tfsprout/version.GitCommit={{.ShortCommit}}
    main: ./cmd/tfsprout
  - binary: tfsproutx
    env:
    - CGO_ENABLED=0
    goos:
    - darwin
    - windows
    - linux
    goarch:
    - amd64
    - "386"
    - arm64
    id: tfsproutx
    ldflags:
    - -s -w -X github.com/jfrappier/tfsprout/version.Version={{.Version}} -X github.com/jfrappier/tfsprout/version.VersionPrerelease= -X github.com/jfrappier/tfsprout/version.GitCommit={{.ShortCommit}}
    main: ./cmd/tfsproutx
changelog:
  disable: true
milestones:
  - close: true
