package passes

import (
	"github.com/jfrappier/tfsprout/passes/AT001"
	"github.com/jfrappier/tfsprout/passes/AT002"
	"github.com/jfrappier/tfsprout/passes/AT003"
	"github.com/jfrappier/tfsprout/passes/AT004"
	"github.com/jfrappier/tfsprout/passes/AT005"
	"github.com/jfrappier/tfsprout/passes/AT006"
	"github.com/jfrappier/tfsprout/passes/AT007"
	"github.com/jfrappier/tfsprout/passes/AT008"
	"github.com/jfrappier/tfsprout/passes/AT009"
	"github.com/jfrappier/tfsprout/passes/AT010"
	"github.com/jfrappier/tfsprout/passes/AT011"
	"github.com/jfrappier/tfsprout/passes/AT012"
	"github.com/jfrappier/tfsprout/passes/R001"
	"github.com/jfrappier/tfsprout/passes/R002"
	"github.com/jfrappier/tfsprout/passes/R003"
	"github.com/jfrappier/tfsprout/passes/R004"
	"github.com/jfrappier/tfsprout/passes/R005"
	"github.com/jfrappier/tfsprout/passes/R006"
	"github.com/jfrappier/tfsprout/passes/R007"
	"github.com/jfrappier/tfsprout/passes/R008"
	"github.com/jfrappier/tfsprout/passes/R009"
	"github.com/jfrappier/tfsprout/passes/R010"
	"github.com/jfrappier/tfsprout/passes/R011"
	"github.com/jfrappier/tfsprout/passes/R012"
	"github.com/jfrappier/tfsprout/passes/R013"
	"github.com/jfrappier/tfsprout/passes/R014"
	"github.com/jfrappier/tfsprout/passes/R015"
	"github.com/jfrappier/tfsprout/passes/R016"
	"github.com/jfrappier/tfsprout/passes/R017"
	"github.com/jfrappier/tfsprout/passes/R018"
	"github.com/jfrappier/tfsprout/passes/R019"
	"github.com/jfrappier/tfsprout/passes/S001"
	"github.com/jfrappier/tfsprout/passes/S002"
	"github.com/jfrappier/tfsprout/passes/S003"
	"github.com/jfrappier/tfsprout/passes/S004"
	"github.com/jfrappier/tfsprout/passes/S005"
	"github.com/jfrappier/tfsprout/passes/S006"
	"github.com/jfrappier/tfsprout/passes/S007"
	"github.com/jfrappier/tfsprout/passes/S008"
	"github.com/jfrappier/tfsprout/passes/S009"
	"github.com/jfrappier/tfsprout/passes/S010"
	"github.com/jfrappier/tfsprout/passes/S011"
	"github.com/jfrappier/tfsprout/passes/S012"
	"github.com/jfrappier/tfsprout/passes/S013"
	"github.com/jfrappier/tfsprout/passes/S014"
	"github.com/jfrappier/tfsprout/passes/S015"
	"github.com/jfrappier/tfsprout/passes/S016"
	"github.com/jfrappier/tfsprout/passes/S017"
	"github.com/jfrappier/tfsprout/passes/S018"
	"github.com/jfrappier/tfsprout/passes/S019"
	"github.com/jfrappier/tfsprout/passes/S020"
	"github.com/jfrappier/tfsprout/passes/S021"
	"github.com/jfrappier/tfsprout/passes/S022"
	"github.com/jfrappier/tfsprout/passes/S023"
	"github.com/jfrappier/tfsprout/passes/S024"
	"github.com/jfrappier/tfsprout/passes/S025"
	"github.com/jfrappier/tfsprout/passes/S026"
	"github.com/jfrappier/tfsprout/passes/S027"
	"github.com/jfrappier/tfsprout/passes/S028"
	"github.com/jfrappier/tfsprout/passes/S029"
	"github.com/jfrappier/tfsprout/passes/S030"
	"github.com/jfrappier/tfsprout/passes/S031"
	"github.com/jfrappier/tfsprout/passes/S032"
	"github.com/jfrappier/tfsprout/passes/S033"
	"github.com/jfrappier/tfsprout/passes/S034"
	"github.com/jfrappier/tfsprout/passes/S035"
	"github.com/jfrappier/tfsprout/passes/S036"
	"github.com/jfrappier/tfsprout/passes/S037"
	"github.com/jfrappier/tfsprout/passes/V001"
	"github.com/jfrappier/tfsprout/passes/V002"
	"github.com/jfrappier/tfsprout/passes/V003"
	"github.com/jfrappier/tfsprout/passes/V004"
	"github.com/jfrappier/tfsprout/passes/V005"
	"github.com/jfrappier/tfsprout/passes/V006"
	"github.com/jfrappier/tfsprout/passes/V007"
	"github.com/jfrappier/tfsprout/passes/V008"
	"github.com/jfrappier/tfsprout/passes/V009"
	"github.com/jfrappier/tfsprout/passes/V010"
	"github.com/jfrappier/tfsprout/passes/V011"
	"github.com/jfrappier/tfsprout/passes/V012"
	"github.com/jfrappier/tfsprout/passes/V013"
	"github.com/jfrappier/tfsprout/passes/V014"
	"golang.org/x/tools/go/analysis"
)

// AllChecks contains all Analyzers that report issues
// This can be consumed via multichecker.Main(passes.AllChecks...) or by
// combining these Analyzers with additional custom Analyzers
var AllChecks = []*analysis.Analyzer{
	AT001.Analyzer,
	AT002.Analyzer,
	AT003.Analyzer,
	AT004.Analyzer,
	AT005.Analyzer,
	AT006.Analyzer,
	AT007.Analyzer,
	AT008.Analyzer,
	AT009.Analyzer,
	AT010.Analyzer,
	AT011.Analyzer,
	AT012.Analyzer,
	R001.Analyzer,
	R002.Analyzer,
	R003.Analyzer,
	R004.Analyzer,
	R005.Analyzer,
	R006.Analyzer,
	R007.Analyzer,
	R008.Analyzer,
	R009.Analyzer,
	R010.Analyzer,
	R011.Analyzer,
	R012.Analyzer,
	R013.Analyzer,
	R014.Analyzer,
	R015.Analyzer,
	R016.Analyzer,
	R017.Analyzer,
	R018.Analyzer,
	R019.Analyzer,
	S001.Analyzer,
	S002.Analyzer,
	S003.Analyzer,
	S004.Analyzer,
	S005.Analyzer,
	S006.Analyzer,
	S007.Analyzer,
	S008.Analyzer,
	S009.Analyzer,
	S010.Analyzer,
	S011.Analyzer,
	S012.Analyzer,
	S013.Analyzer,
	S014.Analyzer,
	S015.Analyzer,
	S016.Analyzer,
	S017.Analyzer,
	S018.Analyzer,
	S019.Analyzer,
	S020.Analyzer,
	S021.Analyzer,
	S022.Analyzer,
	S023.Analyzer,
	S024.Analyzer,
	S025.Analyzer,
	S026.Analyzer,
	S027.Analyzer,
	S028.Analyzer,
	S029.Analyzer,
	S030.Analyzer,
	S031.Analyzer,
	S032.Analyzer,
	S033.Analyzer,
	S034.Analyzer,
	S035.Analyzer,
	S036.Analyzer,
	S037.Analyzer,
	V001.Analyzer,
	V002.Analyzer,
	V003.Analyzer,
	V004.Analyzer,
	V005.Analyzer,
	V006.Analyzer,
	V007.Analyzer,
	V008.Analyzer,
	V009.Analyzer,
	V010.Analyzer,
	V011.Analyzer,
	V012.Analyzer,
	V013.Analyzer,
	V014.Analyzer,
}
